---
title:"wrangling project"
author:"shuochen ding"
date:"2018/4/20"
output:html_documnet
---

```{r setup, include=FALSE}
library(readr)
library(gapminder)
library(stringr)
library(ggplot2)
library(tidyverse)
library(tidytext)
library(lubridate)
library(readxl)
library(rworldmap)
library(ggmap)
library(choroplethr)
library(plotly)
library(later)
library(rvest)
url<-"https://en.wikipedia.org/wiki/List_of_cities_in_Germany_by_population"
```



```{r}
####set up the data I chose
German_city <- url%>%
  read_html()%>%
  html_node("table")%>%
  html_table(fill=TRUE)
operations <- read.csv("C:/Users/Ding Ding/Desktop/operations.csv")%>%as.data.frame()
usa<-operations%>%
  filter(Country =="USA" )
co_na <- colnames(usa)
co_na[16] <- "City"
colnames(usa) <- co_na
```

```{r}
####select out he subset I need
a1<-usa %>%
  select(c(Mission.Date,Country,Air.Force,Aircraft.Series,Target.Country,City,Target.Industry,Target.Priority,Target.Latitude,Target.Longitude,Total.Weight..Tons.))
a2<-German_city%>%
  as.data.frame()%>%
  select(c(2,4,7,8,9))
a2$City <- toupper(a2$City)
german_city_name <- a2$City

german<-left_join(a1%>%filter(City%in%german_city_name),a2,by="City")
head(german)
German_city$`2015 rank`

```

```{r}
####times of bomb attack by each air force
b1 <- german%>%
  mutate(n=1)%>%
  group_by(Air.Force)%>%
  summarise(Air_Force_act_time=sum(n))
b1%>%ggplot(aes(Air.Force,Air_Force_act_time,size = Air_Force_act_time,color = Air.Force))+geom_point()

```

```{r}
####times of each city being bombed
b2<-german%>%
  mutate(n=1)%>%
  group_by(City)%>%
  summarise(City_bomb_time=sum(n))
b2%>%ggplot(aes(City,City_bomb_time,size = City_bomb_time,color = City))+geom_point()
```

```{r}
##pie for top 7 cities being bombed
top_7<-german%>%
  mutate(n=1)%>%
  group_by(City)%>%
  summarise(City_bomb_time=sum(n))%>%
  arrange(desc(City_bomb_time))%>%
  .[1:7,]%>%as.data.frame()
plot_ly(top_7, labels = ~City, values = ~City_bomb_time)%>% add_pie()
```

```{r}
#####total weight of tons of bomb being release on top 7 cities
top_7_bombweight<-german%>%
  select(City,`Total.Weight..Tons.`)%>%
  na.omit()%>%
  filter(City%in%top_7$City)%>%
  group_by(City)%>%
  summarise(Total_bomb_weight=sum(`Total.Weight..Tons.`))%>%
  as.data.frame()
top_7_bombweight%>%ggplot(aes(City,Total_bomb_weight,size = Total_bomb_weight,color = City))+geom_point()
```


```{r}
###most bombed city berlin through timeline
german1<-german
date<-str_split(german1$Mission.Date,"/")
month <- rep(0,nrow(german1))
day <- rep(0,nrow(german1))
year <- rep(0,nrow(german1))
for (i in 1:nrow(german1)) {
  month[i] <- date[[i]][1]
  day[i] <- date[[i]][2]
  year[i] <- date[[i]][3]
}

date1<-(as.numeric(year)-1942)*12+as.numeric(month)
german1$Mission.Date<-date1

german1 <- german1%>%
  mutate(date_bombered=1)
german1$date_bombered <- date1
german1$date_bombered <- as.numeric(german1$date_bombered)
Berlin<-german1%>%
  filter(City=="BERLIN")%>%
  mutate(n=1)%>%
  group_by(date_bombered)%>%
  summarise(bombered_times=sum(n))%>%
  ggplot(aes(date_bombered,bombered_times))+geom_point()+geom_line()+geom_smooth()+ggtitle("Months since 1942,1 with bombed time in Berlin")
Berlin
```

```{r}
####comparing top bombed city through time line
top_4<-top_7[1:4,]
german1%>%
  filter(City%in%top_4$City)%>%
  group_by(date_bombered,City)%>%
  mutate(n=1)%>%
  summarise(attack_of_city=sum(n))%>%
  na.omit()%>%
  ggplot(aes(date_bombered, attack_of_city, colour = City)) + geom_point() + geom_line() +
  facet_wrap( ~ City, nrow = 4) + ggtitle("top bombered city in the time line") +
  xlab("month") + ylab("Number") + theme(legend.position = "none")
```

```{r}
####top 8 bombed industry in german
top_8<-german%>%
  mutate(n=1)%>%
  group_by(Target.Industry)%>%
  summarise(Industry_bomb_time=sum(n))%>%
  arrange(desc(Industry_bomb_time))%>%
  .[1:8,]%>%as.data.frame()
ggplot(top_8,aes(Target.Industry,Industry_bomb_time))+geom_bar(stat="identity",fill="steelblue")+coord_flip()+geom_text(aes(label=Industry_bomb_time),hjust=0.5)
```

```{r}
####priority distribution in pir for each industry

####railroad
Industry1<-german%>%
  filter(str_detect(Target.Industry,"RR"))
Industry1_rank<-Industry1[,7:8]
Industry1_pie<-Industry1_rank%>%
  mutate(n=1)%>%
  group_by(Target.Priority)%>%
  summarise(Priority_time=sum(n))%>%
  arrange(desc(Priority_time))%>%
  .[1:5,]%>%as.data.frame()
plot_ly(Industry1_pie, labels = ~Target.Priority, values = ~Priority_time)%>% add_pie()
#####aircraft
Industry2<-german%>%
 filter(Target.Industry =="AIRCRAFT FACTORIES AND ASSEMBLY PLANTS" )
Industry2_rank<-Industry2[,7:8]
Industry2_pie<-Industry2_rank%>%
  mutate(n=1)%>%
  group_by(Target.Priority)%>%
  summarise(Priority_time=sum(n))%>%
  arrange(desc(Priority_time))%>%
  .[1:5,]%>%as.data.frame()
plot_ly(Industry2_pie, labels = ~Target.Priority, values = ~Priority_time)%>% add_pie()
####armament
Industry3<-german%>%
 filter(Target.Industry =="ARMAMENT AND ORDNANCE PLANTS" )
Industry3_rank<-Industry3[,7:8]
Industry3_pie<-Industry3_rank%>%
  mutate(n=1)%>%
  group_by(Target.Priority)%>%
  summarise(Priority_time=sum(n))%>%
  arrange(desc(Priority_time))%>%
  .[1:5,]%>%as.data.frame()
plot_ly(Industry3_pie, labels = ~Target.Priority, values = ~Priority_time)%>% add_pie()
#####city and urban
Industry4<-german%>%
 filter(Target.Industry =="CITIES TOWNS AND URBAN AREAS" )
Industry4_rank<-Industry4[,7:8]
Industry4_pie<-Industry4_rank%>%
  mutate(n=1)%>%
  group_by(Target.Priority)%>%
  summarise(Priority_time=sum(n))%>%
  arrange(desc(Priority_time))%>%
  .[1:5,]%>%as.data.frame()
plot_ly(Industry4_pie, labels = ~Target.Priority, values = ~Priority_time)%>% add_pie()
######vehicle
Industry5<-german%>%
 filter(Target.Industry =="VEHICLE MFG. PLANTS" )
Industry5_rank<-Industry5[,7:8]
Industry5_pie<-Industry5_rank%>%
  mutate(n=1)%>%
  group_by(Target.Priority)%>%
  summarise(Priority_time=sum(n))%>%
  arrange(desc(Priority_time))%>%
  .[1:5,]%>%as.data.frame()
plot_ly(Industry5_pie, labels = ~Target.Priority, values = ~Priority_time)%>% add_pie()
#######tank factories
Industry6<-german%>%
 filter(Target.Industry =="TANK FACTORIES" )
Industry6_rank<-Industry6[,7:8]
Industry6_pie<-Industry6_rank%>%
  mutate(n=1)%>%
  group_by(Target.Priority)%>%
  summarise(Priority_time=sum(n))%>%
  arrange(desc(Priority_time))%>%
  .[1:5,]%>%as.data.frame()
plot_ly(Industry6_pie, labels = ~Target.Priority, values = ~Priority_time)%>% add_pie()
#######supply and warehouse
Industry7<-german%>%
 filter(Target.Industry =="SUPPLY DUMPS AND WAREHOUSES" )
Industry7_rank<-Industry7[,7:8]
Industry7_pie<-Industry7_rank%>%
  mutate(n=1)%>%
  group_by(Target.Priority)%>%
  summarise(Priority_time=sum(n))%>%
  arrange(desc(Priority_time))%>%
  .[1:5,]%>%as.data.frame()
plot_ly(Industry7_pie, labels = ~Target.Priority, values = ~Priority_time)%>% add_pie()
####overall percentage
priority1<-nrow(german%>%
  filter(Target.Priority == 1))
priority2<-nrow(german%>%
  filter(Target.Priority == 2))
priority3<-nrow(german%>%
  filter(Target.Priority == 3))
priority4<-nrow(german%>%
  filter(Target.Priority == 4))
first_per=priority1/nrow(german)
second_per=priority2/nrow(german)
third_per=priority3/nrow(german)
fourth_per=priority4/nrow(german)

```

```{r}
###  city recovery from warII in terms of population density based on times of bombed during war
city_dense<-left_join(b2,a2,by="City")
a11 <- city_dense%>%
  str_split("km2","`2015 population density`")
a3 <- rep(0,25)
a11 <- str_split(city_dense$`2015 population density`,"km2")
for(i in 1:25){
  a3[i]=a11[[i]][1]
}
a3 <- a3%>%str_extract_all("[0-9]+")
for (i in 1:25) {
  a3[[i]] <- a3[[i]][1]%>%str_glue(a3[[i]][2])
}
a4 <- rep(0,25)
for (i in 1:25) {
  a4[i] <- a3[[i]][1]
}
city_dense$`2015 population density` <-a4%>%str_extract_all("[0-9]+")%>%as.numeric()
lm<-lm(city_dense$`2015 population density`~b2$City_bomb_time)
temp <- lm$fitted.values
city_dense <- city_dense%>%mutate(predict=temp)
plot(city_dense$`2015 population density`,b2$City_bomb_time)

```


```{r}
##Months since 1942,1 with bombed time
#####
  german1%>%
  mutate(n=1)%>%
  group_by(date_bombered)%>%
  summarise(time_bombered_day=sum(n))%>%
  ggplot(aes(date_bombered,time_bombered_day))+geom_point()+geom_line()+geom_smooth()+ggtitle("Months since 1942,1 with bombed time")


```

```{r}
###Months since 1942,1 with bombed time
date3<-((as.numeric(year)-1942)*12+as.numeric(month))%>%as.character()
german3<-german
german3$Mission.Date<-date3
german3 <- german3%>%mutate(date_bombered=1)
german3$date_bombered <- date3
german3%>%
  mutate(n=1)%>%
  group_by(date_bombered)%>%
  summarise(time_bombered_day=sum(n))%>%
  ggplot(aes(date_bombered,time_bombered_day))+geom_density()+ggtitle("Months since 1942,1 with bombed time")
```
